### PR TITLE
docs(experiments): add s3 dataset downloading

### PR DESCRIPTION
**Pull request by bbatha**
Marked WIP so that we can add cli documentation and to make the sdk examples correct.

### CODE REVIEW

**Comment by bbatha** [comment]
@jaredscheib do you know which top-level document should link to this one?

**Comment by jaredscheib** [comment]
i'd put this under Data, as the last section, and a mention & link to it under Experiments/About

**Comment by bbatha** [comment]
@mkulaczkowski have you been able to figure out the multiple datasets cli options? @BartoszCki would you be able to help out with making the examples accurate for the cli?

**Comment by dte** [comment]
> @mkulaczkowski have you been able to figure out the multiple datasets cli options? @BartoszCki would you be able to help out with making the examples accurate for the cli?

@mkulaczkowski shared this:
```
gradient experiments run singlenode --projectId p123456 --name=datasettest --vpc --clusterId abcd1234 --datasetUri "s3://testbuckfortesting/" --container "tensorflow/tensorflow:1.13.1-py3" --command "pip install -r requirements.txt && python mnist.py" --machineType V100 --workspace https://github.com/Paperspace/mnist-sample.git --datasetAwsAccessKeyId test --datasetAwsSecretAccessKey test --datasetName testbucket --datasetVersionId 1 --datasetEtag 1
```

**Comment by dkobran** [comment]
@mkulaczkowski @BartoszCki We need CLI examples in the docs for users and for internal testing. This PR does not provide the user (or our own team) with enough information to use/test this feature.  I see that @dte has received _a_ command but it seems unlikely that this is the only command related to S3 dataset mounting. Please send along asap.

**Comment by sanfilip** [comment]
Hey everyone needs to respond to these or comments when tagged!!!! We are dropping these questions on the flor.  dan has been blocked on this for literally days.  No one is testing datasets from the cli because Dan can't get answers.   I've asked John Oberly to take this on.  I'm reopening this PR.

**Comment by sanfilip** [comment]
Please consider this PR not finished.  This is abosolutely urgent to priory to get done!!!

**Comment by mkulaczkowski** [comment]
@sanfilip We were waiting to validate datasets behaviour first on CLI side that takes the precedence. I am going to provide more examples but its lower on my list of priorities.

**Comment by joberly** [comment]
At first glance, it looks like the following options all take lists:
- datasetUri
- datasetName
- datasetAwsAccessKeyId
- datasetAwsSecretAccessKey
- datasetVersionId
- datasetEtag

Still looking at how all of these lists match up but the only way it seems to make sense is if they are parallel lists.

**Comment by joberly** [comment]
I have not tried this yet, but from one of the CLI tests it does look like that's how it was intended to work. So here's an example from what I gathered from the tests:

```
gradient experiments run singlenode --projectId p123456 
  --name=datasettest --vpc --clusterId abcd1234 
  --datasetUri "s3://dataset-1/object" 
  --datasetName "dataset 1" 
  --datasetAwsAccessKeyId "dataset-1-id" 
  --datasetAwsSecretAccessKey "dataset-1-secret" 
  --datasetVersionId "dataset-1-object-version" 
  --datasetEtag "dataset-1-object-etag"
  --datasetUri "s3://dataset-2/object" 
  --datasetName "dataset 2" 
  --datasetAwsAccessKeyId "dataset-2-id" 
  --datasetAwsSecretAccessKey "dataset-2-secret" 
  --datasetVersionId "dataset-2-object-version" 
  --datasetEtag "dataset-2-object-etag"
```

**Comment by sanfilip** [comment]
@joberly is there an option for specifying the dataset size or the dataset type ("shared", no shared)?  I thought we needed the dataset size in cases where the user has determined that their dataset will not fix in the default 5GB volume.  For type, are we always defaulting to shared now? cc @bbatha

**Comment by joberly** [comment]
Adding to the above, in the event that the user does not want to specify a value for a particular dataset option, e.g. no version ID or no ETag, the user must specify "none". Here's another example:

```
gradient experiments run singlenode 
  --projectId p123456 
  --name=datasettest --vpc --clusterId abcd1234 
  --datasetUri "s3://dataset-1/object" 
  --datasetName "dataset 1" 
  --datasetAwsAccessKeyId "dataset-1-id" 
  --datasetAwsSecretAccessKey "dataset-1-secret" 
  --datasetVersionId "dataset-1-object-version" 
  --datasetEtag "dataset-1-object-etag"
  --datasetUri "s3://dataset-2/object" 
  --datasetName "dataset 2" 
  --datasetAwsAccessKeyId "dataset-2-id" 
  --datasetAwsSecretAccessKey "dataset-2-secret" 
  --datasetVersionId "none" 
  --datasetEtag "none"
  --datasetUri "s3://dataset-3/object" 
  --datasetName "dataset 3" 
  --datasetAwsAccessKeyId "dataset-3-id" 
  --datasetAwsSecretAccessKey "dataset-3-secret" 
  --datasetVersionId "dataset-3-object-version" 
  --datasetEtag "dataset-3-object-etag"
```

**Comment by sanfilip** [comment]
Also @joberly in the case where you have multiple datasets, are the parameters for the second and subsequent datasets just determined by option ordering on the command line?  I'd be surprised if for "dataset 2" the other parameters had to be preceeded by the same name but with spaces turned to underscores.  I think this is just test data:
  --datasetName "dataset 2" 
  --datasetAwsAccessKeyId "dataset-2-id" 
  --datasetAwsSecretAccessKey "dataset-2-secret"

**Comment by joberly** [comment]
> @joberly is there an option for specifying the dataset size or the dataset type ("shared", no shared)? I thought we needed the dataset size in cases where the user has determined that their dataset will not fix in the default 5GB volume. For type, are we always defaulting to shared now? cc @bbatha

I haven't found any options for dataset size or type. The code that creates the list of dataset options only references URI, name, access key id, secret access key, version ID, and ETag.

**Comment by joberly** [comment]
> Also @joberly in the case where you have multiple datasets, are the parameters for the second and subsequent datasets just determined by option ordering on the command line? I'd be surprised if for "dataset 2" the other parameters had to be preceeded by the same name but with spaces turned to underscores. I think this is just test data:
> --datasetName "dataset 2"
> --datasetAwsAccessKeyId "dataset-2-id"
> --datasetAwsSecretAccessKey "dataset-2-secret"

Yes, order on the command line determines which URI matches which name, access key ID, etc. The "dataset X" values above were just my way of trying to show how the options relate to one another. :)

So for example, if I have the following datasets:
- Name: dataset A
  - URI: s3://my-first-dataset/object
  - Access Key ID: abc123
  - Secret Access Key: def456
  - Version ID: abababab
  - ETag: cdcdcdcd
- Name: dataset B
  - URI: s3://some-other-dataset/dir
  - Access Key ID: aaa111
  - Secret Access Key: bbb222
  - Version ID: none
  - ETag: none

Here's the command:
```
gradient experiments run singlenode 
  --projectId p123456 
  --name=datasettest --vpc --clusterId abcd1234 
  --datasetUri "s3://my-first-dataset/object" 
  --datasetName "dataset A" 
  --datasetAwsAccessKeyId "abc123" 
  --datasetAwsSecretAccessKey "def456" 
  --datasetVersionId "abababab" 
  --datasetEtag "cdcdcdcd"
  --datasetUri "s3://some-other-dataset/dir" 
  --datasetName "dataset B" 
  --datasetAwsAccessKeyId "aaa111" 
  --datasetAwsSecretAccessKey "bbb222" 
  --datasetVersionId "none" 
  --datasetEtag "none"
```

**Comment by mkutsovsky** [comment]
Fyi The sdk / config.yaml are much nicer for multiple datatsets. It is just an array of dicts

**Comment by sanfilip** [comment]
@bbatha
>>@joberly is there an option for specifying the dataset size or the dataset type ("shared", no shared)? I thought we needed the dataset size in cases where the user has determined that their dataset will not fix in the default 5GB volume. For type, are we always defaulting to shared now? cc @bbatha
>I haven't found any options for dataset size or type. The code that creates the list of dataset options only references URI, name, access key id, secret access key, version ID, and ETag.

Won't we need a dataset size parameter realistically?

**Comment by joberly** [comment]
Note that the `--vpc` option is needed to create a V2 experiment.

**Comment by bbatha** [comment]
The operator and dispatcher support a `volumeOptions` object as part of the dataset params. It can be configured like so:

default:
```
volumeOptions:
   kind: dynamic
   size: 5Gi
```

shared:
```
volumeOptions:
     kind: shared
```

I don't know if these options made it to experiments or the cli.

**Comment by bbatha** [comment]
> Note that the --vpc option is needed to create a V2 experiment.

This is currently the case but there is an open ticket to remove it and make the experiments-api no longer use it. PS-12380

**Pull request merged**
